ServerEvents.recipes(event => {
    event.replaceInput({ id: 'tfmg:sequenced_assembly/turbine_engine' }, 'tfmg:screwdriver', '#forge:screwdrivers')
    event.replaceInput({ id: 'tfmg:sequenced_assembly/lpg_engine' }, 'tfmg:screwdriver', '#forge:screwdrivers')
    event.replaceInput({ id: 'tfmg:sequenced_assembly/turbine_engine' }, 'tfmg:screwdriver', '#forge:screwdrivers')
    event.replaceInput({ id: 'tfmg:sequenced_assembly/steel_mechanism' }, 'tfmg:screwdriver', '#forge:screwdrivers')
    event.replaceInput({ id: 'functionalstorage:gold_upgrade' }, 'functionalstorage:copper_upgrade', 'kubejs:brass_machine')
    event.replaceInput({ id: 'functionalstorage:gold_upgrade' }, 'minecraft:gold_block', 'create:brass_block')
    event.replaceInput({ id: 'functionalstorage:gold_upgrade' }, 'minecraft:gold_ingot', 'create:brass_ingot')
    event.replaceInput({ id: 'functionalstorage:copper_upgrade' }, '#functionalstorage:drawer', 'kubejs:copper_machine')
    event.replaceInput({ id: 'functionalstorage:armory_cabinet' }, 'minecraft:comparator', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create_sa:experience_pickaxe_recipe' }, 'create_sa:zinc_handle', 'vintageimprovements:zinc_rod')
    event.replaceInput({ id: 'create_sa:experience_sword_recipe' }, 'create_sa:zinc_handle', 'vintageimprovements:zinc_rod')
    event.replaceInput({ id: 'create_sa:experience_shovel_recipe' }, 'create_sa:zinc_handle', 'vintageimprovements:zinc_rod')
    event.replaceInput({ id: 'create_sa:experience_axe_recipe' }, 'create_sa:zinc_handle', 'vintageimprovements:zinc_rod')
    event.replaceInput({ id: 'delightful:knives/experience_knife' }, 'create_sa:zinc_handle', 'vintageimprovements:zinc_rod')
    event.replaceInput({ id: 'createaddition:crafting/rolling_mill' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ input: 'alexscaves:limestone' }, 'alexscaves:limestone', 'create:limestone')
    event.replaceInput({ input: 'quark:limestone' }, 'quark:limestone', 'create:limestone')
    event.replaceOutput({ output: 'alexscaves:limestone' }, 'alexscaves:limestone', 'create:limestone')
    event.replaceOutput({ output: 'quark:limestone' }, 'quark:limestone', 'create:limestone')
    event.replaceInput({ id: 'create:crafting/kinetics/brass_hand' }, 'create:brass_sheet', '#minecraft:wooden_slabs')
    event.replaceInput({ input: 'tfmg:steel_casing' }, 'tfmg:steel_casing', 'create_dd:steel_casing')
    event.replaceInput({ id: 'create:crafting/kinetics/mechanical_crafter' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create:crafting/kinetics/mechanical_arm' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create:crafting/kinetics/rotation_speed_controller' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/command_seat' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create:crafting/logistics/stockpile_switch' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create:crafting/logistics/content_observer' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/alt_meter' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create:crafting/kinetics/elevator_pulley' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'numismatics:crafting/vendor' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'numismatics:crafting/brass_depositor' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'vintageimprovements:craft/laser' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'createpropulsion:crafting/optical_sensor' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'createpropulsion:crafting/lodestone_tracker' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceOutput({ id: 'create:crafting/kinetics/mechanical_crafter' }, 'create:mechanical_crafter', '4x create:mechanical_crafter')
    event.replaceOutput({ id: 'create:crafting/kinetics/mechanical_arm' }, 'create:mechanical_arm', '2x create:mechanical_arm')
    event.replaceOutput({ id: 'create:crafting/logistics/stockpile_switch' }, 'create:stockpile_switch', '2x create:stockpile_switch')
    event.replaceOutput({ id: 'create:crafting/logistics/content_observer' }, 'create:content_observer', '2x create:content_observer')
    event.replaceInput({ id: 'create:crafting/kinetics/smart_chute' }, 'create:brass_sheet', 'create_dd:integrated_mechanism')
    event.replaceInput({ id: 'computercraft:pocket_computer_advanced' }, 'minecraft:golden_apple', 'create_dd:linked_controller')
    event.replaceInput({ id: 'vintageimprovements:craft/vacuum_chamber' }, 'create:andesite_casing', 'kubejs:copper_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/mechanical/gravitron' }, 'create:iron_sheet', 'create_dd:shadow_steel_sheet')
    event.replaceInput({ id: 'vs_clockwork:crafting/mechanical/gravitron' }, 'create:mechanical_pump', 'kubejs:steel_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/flap_bearing' }, 'create:andesite_casing', 'kubejs:steel_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/phys_bearing' }, 'create:andesite_casing', 'kubejs:steel_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/propeller_bearing' }, 'create:andesite_casing', 'kubejs:steel_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/redstone_resistor' }, 'create:andesite_casing', 'kubejs:copper_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/physics_infuser' }, 'create:sturdy_sheet', 'create_dd:steel_sheet')
    event.replaceInput({ input: 'createnuclear:lead_ingot' }, 'createnuclear:lead_ingot', '#forge:ingots/lead')
    event.replaceInput({ input: 'createnuclear:steel_ingot' }, 'createnuclear:steel_ingot', '#forge:ingots/steel')
    event.replaceInput({ id: 'sophisticatedbackpacks:upgrade_base' }, 'minecraft:iron_ingot', 'create_dd:tin_ingot')
    event.replaceInput({ id: 'sophisticatedbackpacks:upgrade_base' }, 'minecraft:string', 'create_dd:andesite_sheet')
    event.replaceInput({ id: 'create_dd:crafting/lapis_alloy' }, 'create_dd:tin_nugget', 'minecraft:iron_nugget')
    event.replaceInput({ id: 'createbigcannons:sequenced_assembly/bronze_autocannon_breech_extractor' }, '#createbigcannons:ingot_bronze', '#forge:ingots/strong_bronze')
    event.replaceInput({ id: 'createbigcannons:cannon_drill' }, 'create:andesite_casing', 'kubejs:copper_machine')
    event.replaceInput({ id: 'createbigcannons:cannon_loader' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'numismatics:crafting/andesite_depositor' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'numismatics:crafting/bank_terminal' }, 'create:industrial_iron_block', 'kubejs:steel_machine')
    event.replaceInput({ id: 'createbigcannons:cannon_loader' }, 'minecraft:gunpowder', 'create_dd:industrial_iron_sheet')
    event.replaceInput({ id: 'createbigcannons:cannon_mount_extension' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'createbigcannons:cannon_mount_extension' }, 'minecraft:gunpowder', 'create_dd:industrial_iron_sheet')
    event.replaceInput({ id: 'createbigcannons:fixed_cannon_mount' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'createbigcannons:fixed_cannon_mount' }, 'minecraft:gunpowder', 'create_dd:industrial_iron_sheet')
    event.replaceInput({ id: 'create_connected:crafting/kinetics/freewheel_clutch' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'create_connected:crafting/kinetics/overstress_clutch' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'create_connected:crafting/kinetics/centrifugal_clutch' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'vintageimprovements:craft/curving_press' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'create_connected:crafting/kinetics/brake' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'create_connected:crafting/kinetics/inventory_access_port' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceOutput({ id: 'create_connected:crafting/kinetics/inventory_access_port' }, 'create_connected:inventory_access_port', '4x create_connected:inventory_access_port')
    event.replaceInput({ id: 'create_radar:crafting/monitor' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'tfmg:crafting/pumpjack_hammer_head' }, 'tfmg:steel_block', 'create_dd:steel_block')
    event.replaceInput({ id: 'tfmg:crafting/steel_from_block' }, 'tfmg:steel_block', 'create_dd:steel_block')
    event.replaceInput({ input: 'createdeco:industrial_steel_sheet' }, 'createdeco:industrial_steel_sheet', 'create_dd:industrial_steel_sheet')
    event.replaceInput({ input: 'createdeco:andesite_sheet' }, 'createdeco:andesite_sheet', 'create_dd:andesite_sheet')
    event.replaceInput({ id: 'toms_peripherals:gpu' }, 'toms_peripherals:gpu_chip', 'kubejs:graphics_unit')
    event.replaceInput({ id: 'toms_peripherals:laser_pointer' }, 'minecraft:amethyst_shard', 'vintageimprovements:laser_item')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/alt_meter' }, 'minecraft:redstone', 'kubejs:nickel_tube')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/alt_meter' }, 'minecraft:string', 'create:precision_mechanism')
    event.replaceOutput({ id: 'vs_tournament:ballast' }, 'vs_tournament:ballast', 'vs_clockwork:ballast')
    event.replaceInput({ id: 'railways:crafting/handcar' }, 'create:cogwheel', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'create_enchantment_industry:crafting/printer' }, 'create:copper_casing', 'kubejs:copper_machine')
    event.replaceInput({ id: 'northstar:mechanical_crafting/interplanetary_navigator' }, 'create:iron_sheet', 'create_dd:steel_sheet')
    event.replaceInput({ id: 'vintageimprovements:mechanical_crafting/laser' }, 'create:copper_sheet', 'create_dd:rubber')
    event.replaceInput({ id: 'northstar:mechanical_crafting/electrolysis_machine' }, 'create:fluid_tank', 'kubejs:blazing_machine')
    event.replaceInput({ id: 'northstar:mechanical_crafting/electrolysis_machine' }, 'create:fluid_pipe', 'tfmg:steel_pipe')
    event.replaceInput({ id: 'northstar:mechanical_crafting/oxygen_concentrator' }, 'create:iron_sheet', 'create_dd:steel_sheet')
    event.replaceInput({ id: 'northstar:mechanical_crafting/oxygen_concentrator' }, '#minecraft:wool', 'tconstruct:silky_cloth')
    event.replaceInput({ id: 'northstar:mechanical_crafting/oxygen_concentrator' }, 'create:fluid_tank', 'kubejs:steel_machine')
    event.replaceInput({ id: "northstar:mechanical_crafting/targeting_computer_rack" }, 'create:iron_sheet', 'create_dd:steel_sheet')
    event.replaceInput({ id: "northstar:mechanical_crafting/targeting_computer_rack" }, 'minecraft:iron_ingot', 'tfmg:steel_ingot')
    event.replaceInput({ id: "northstar:mechanical_crafting/oxygen_generator" }, 'create:fluid_tank', 'kubejs:steel_machine')
    event.replaceInput({ id: "northstar:mechanical_crafting/oxygen_generator" }, 'create:iron_sheet', 'create_dd:steel_sheet')
    event.replaceInput({ id: "northstar:mechanical_crafting/oxygen_generator" }, 'create:encased_fan', 'create_dd:industrial_fan')
    event.replaceInput({ id: "northstar:oxygen_filler" }, 'create:iron_sheet', 'create_dd:steel_sheet')
    event.replaceInput({ id: "northstar:oxygen_filler" }, 'create:fluid_tank', 'kubejs:steel_machine')
    event.replaceInput({ id: "northstar:oxygen_filler" }, 'minecraft:iron_ingot', 'tfmg:steel_ingot')
    event.replaceInput({ id: "tconstruct:smeltery/alloys/molten_slimesteel" }, '#forge:molten_iron', '#forge:molten_steel')
    event.replaceInput({ id: "northstar:oxygen_detector" }, '#minecraft:wool', 'kubejs:steel_machine')
    event.replaceInput({ id: "northstar:iron_space_door" }, 'create:iron_sheet', 'create_dd:steel_sheet')
    event.replaceInput({ id: "northstar:sequenced_assembly/targeting_computer" }, 'create:iron_sheet', 'kubejs:motherboard')
    event.replaceInput({ id: "northstar:sequenced_assembly/targeting_computer" }, 'create:precision_mechanism', "create_dd:abstruse_mechanism")
    event.replaceInput({ id: "create:crafting/kinetics/contraption_controls" }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: "northstar:sequenced_assembly/circuit" }, 'create:iron_sheet', 'create_dd:steel_sheet')
    event.replaceInput({ id: "northstar:ice_box" }, 'create:iron_sheet', "create_dd:steel_sheet")
    event.replaceInput({ id: "trackwork:med_simple_wheel" }, 'create:mechanical_piston', 'vintageimprovements:small_steel_spring')
    event.replaceInput({ id: "trackwork:simple_wheel" }, 'create:mechanical_piston', 'vintageimprovements:steel_spring')
    event.replaceInput({ id: "create_dd:crafting/bronze_drill" }, 'tfmg:steel_ingot', 'create:mechanical_drill')
    event.replaceInput({ id: "create_dd:crafting/bronze_saw" }, 'tfmg:steel_ingot', 'create:mechanical_saw')
    event.replaceInput({ id: "railways:crafting/semaphore" }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: "vintageimprovements:craft/centrifuge" }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: "vintageimprovements:craft/belt_grinder" }, 'create:mechanical_mixer', 'kubejs:steel_machine')
    event.replaceInput({ id: "tfmg:crafting/low_grade_fuel_engine" }, 'create:large_cogwheel', 'create_dd:steel_cogwheel')

    
    let sids = [
        'tfmg:crafting/diesel_engine_expansion',
        'tfmg:mechanical_crafting/surface_scanner',
        'tfmg:mechanical_crafting/diesel_engine',
        'tfmg:mechanical_crafting/large_radial_engine',
        'tfmg:mechanical_crafting/radial_engine',
        'tfmg:mechanical_crafting/steel_distillation_controller',
        'tfmg:mechanical_crafting/engine_base'

    ]
    sids.forEach((id) => {
        event.replaceInput({ id: id }, 'tfmg:heavy_machinery_casing', 'kubejs:steel_machine')
    })
})