ServerEvents.recipes(event => {
    event.replaceInput({ id: 'tfmg:sequenced_assembly/turbine_engine' }, 'tfmg:screwdriver', '#forge:screwdrivers')
    event.replaceInput({ id: 'tfmg:sequenced_assembly/lpg_engine' }, 'tfmg:screwdriver', '#forge:screwdrivers')
    event.replaceInput({ id: 'tfmg:sequenced_assembly/turbine_engine' }, 'tfmg:screwdriver', '#forge:screwdrivers')
    event.replaceInput({ id: 'tfmg:sequenced_assembly/steel_mechanism' }, 'tfmg:screwdriver', '#forge:screwdrivers')
    event.replaceInput({ id: 'functionalstorage:gold_upgrade' }, 'functionalstorage:copper_upgrade', 'kubejs:brass_machine')
    event.replaceInput({ id: 'functionalstorage:gold_upgrade' }, 'minecraft:gold_block', 'create:brass_block')
    event.replaceInput({ id: 'functionalstorage:gold_upgrade' }, 'minecraft:gold_ingot', 'create:brass_ingot')
    event.replaceInput({ id: 'functionalstorage:copper_upgrade' }, '#functionalstorage:drawer', 'kubejs:copper_machine')
    event.replaceInput({ id: 'functionalstorage:armory_cabinet' }, 'minecraft:comparator', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create_sa:experience_pickaxe_recipe' }, 'create_sa:zinc_handle', 'vintageimprovements:zinc_rod')
    event.replaceInput({ id: 'create_sa:experience_sword_recipe' }, 'create_sa:zinc_handle', 'vintageimprovements:zinc_rod')
    event.replaceInput({ id: 'create_sa:experience_shovel_recipe' }, 'create_sa:zinc_handle', 'vintageimprovements:zinc_rod')
    event.replaceInput({ id: 'create_sa:experience_axe_recipe' }, 'create_sa:zinc_handle', 'vintageimprovements:zinc_rod')
    event.replaceInput({ id: 'delightful:knives/experience_knife' }, 'create_sa:zinc_handle', 'vintageimprovements:zinc_rod')
    event.replaceInput({ id: 'createaddition:crafting/rolling_mill' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ input: 'alexscaves:limestone' }, 'alexscaves:limestone', 'create:limestone')
    event.replaceInput({ input: 'quark:limestone' }, 'quark:limestone', 'create:limestone')
    event.replaceOutput({ output: 'alexscaves:limestone' }, 'alexscaves:limestone', 'create:limestone')
    event.replaceOutput({ output: 'quark:limestone' }, 'quark:limestone', 'create:limestone')
    event.replaceInput({ id: 'create:crafting/kinetics/brass_hand' }, 'create:brass_sheet', '#minecraft:wooden_slabs')
    event.replaceInput({ input: 'tfmg:steel_casing' }, 'tfmg:steel_casing', 'create_dd:steel_casing')
    event.replaceInput({ id: 'create:crafting/kinetics/mechanical_crafter' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create:crafting/kinetics/mechanical_arm' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create:crafting/kinetics/rotation_speed_controller' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/command_seat' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create:crafting/logistics/stockpile_switch' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create:crafting/logistics/content_observer' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/alt_meter' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create:crafting/kinetics/smart_chute' }, 'create:brass_sheet', 'create_dd:integrated_mechanism')
    event.replaceInput({ id: 'computercraft:pocket_computer_advanced' }, 'minecraft:golden_apple', 'create_dd:linked_controller')
    event.replaceInput({ id: 'vintageimprovements:craft/vacuum_chamber' }, 'create:andesite_casing', 'kubejs:copper_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/mechanical/gravitron' }, 'create:iron_sheet', 'create_dd:shadow_steel_sheet')
    event.replaceInput({ id: 'vs_clockwork:crafting/mechanical/gravitron' }, 'create:mechanical_pump', 'kubejs:steel_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/flap_bearing' }, 'create:andesite_casing', 'kubejs:steel_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/phys_bearing' }, 'create:andesite_casing', 'kubejs:steel_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/propeller_bearing' }, 'create:andesite_casing', 'kubejs:steel_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/redstone_resistor' }, 'create:andesite_casing', 'kubejs:copper_machine')
    event.replaceInput({ id: 'vs_clockwork:crafting/kinetics/physics_infuser' }, 'create:sturdy_sheet', 'create_dd:steel_sheet')
    event.replaceInput({ input: 'createnuclear:lead_ingot' }, 'createnuclear:lead_ingot', '#forge:ingots/lead')
    event.replaceInput({ input: 'createnuclear:steel_ingot' }, 'createnuclear:steel_ingot', '#forge:ingots/steel')
    event.replaceInput({ id: 'sophisticatedbackpacks:upgrade_base' }, 'minecraft:iron_ingot', 'create_dd:tin_ingot')
    event.replaceInput({ id: 'sophisticatedbackpacks:upgrade_base' }, 'minecraft:string', 'create_dd:andesite_sheet')
    event.replaceInput({ id: 'create_dd:crafting/lapis_alloy' }, 'create_dd:tin_nugget', 'minecraft:iron_nugget')
    event.replaceInput({ id: 'createbigcannons:sequenced_assembly/bronze_autocannon_breech_extractor' }, '#createbigcannons:ingot_bronze', '#forge:ingots/strong_bronze')
    event.replaceInput({ id: 'createbigcannons:cannon_drill' }, 'create:andesite_casing', 'kubejs:copper_machine')
    event.replaceInput({ id: 'createbigcannons:cannon_loader' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'createbigcannons:cannon_loader' }, 'minecraft:gunpowder', 'create_dd:industrial_iron_sheet')
    event.replaceInput({ id: 'createbigcannons:cannon_mount_extension' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'createbigcannons:cannon_mount_extension' }, 'minecraft:gunpowder', 'create_dd:industrial_iron_sheet')
    event.replaceInput({ id: 'createbigcannons:fixed_cannon_mount' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'createbigcannons:fixed_cannon_mount' }, 'minecraft:gunpowder', 'create_dd:industrial_iron_sheet')
    event.replaceInput({ id: 'create_connected:crafting/kinetics/freewheel_clutch' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'create_connected:crafting/kinetics/overstress_clutch' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'create_connected:crafting/kinetics/centrifugal_clutch' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'create_connected:crafting/kinetics/brake' }, 'create:andesite_casing', 'kubejs:andesite_machine')
    event.replaceInput({ id: 'create_connected:crafting/kinetics/inventory_access_port' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'create_radar:crafting/monitor' }, 'create:brass_casing', 'kubejs:brass_machine')
    event.replaceInput({ id: 'tfmg:crafting/pumpjack_hammer_head' }, 'tfmg:steel_block', 'create_dd:steel_block')
    event.replaceInput({ id: 'tfmg:crafting/steel_from_block' }, 'tfmg:steel_block', 'create_dd:steel_block')

    
    let sids = [
        'tfmg:crafting/diesel_engine_expansion',
        'tfmg:mechanical_crafting/surface_scanner',
        'tfmg:mechanical_crafting/diesel_engine',
        'tfmg:mechanical_crafting/large_radial_engine',
        'tfmg:mechanical_crafting/radial_engine',
        'tfmg:mechanical_crafting/steel_distillation_controller',
        'tfmg:mechanical_crafting/engine_base'

    ]
    sids.forEach((id) => {
        event.replaceInput({ id: id }, 'tfmg:heavy_machinery_casing', 'kubejs:steel_machine')
    })
})