ServerEvents.recipes(event => {
    let recipeIds = [
        'vintageimprovements:pressurizing/sulfuric_acid',
        'vintageimprovements:pressurizing/copper_sulfate',
        'tfmg:mixing/sulfuric_acid',
        'createaddition:mixing/netherrack',
        'create_sa:netherrack_recipe',
        'tfmg:mixing/zinc_sulfate',
        'tfmg:mixing/copper_sulfate',
        'create:mixing/brass_ingot',
        'create:crafting/materials/electron_tube',
        'tconstruct:smeltery/alloys/molten_brass',
        'tconstruct:smeltery/entity_melting/bee',
        'tconstruct:smeltery/melting/slime/honey_block',
        'create:item_application/brass_casing_from_log_using_deployer',
        'create:item_application/brass_casing_from_wood_using_deployer',
        'create:item_application/brass_casing_from_wood',
        'create:item_application/brass_casing_from_log',
        'create:item_application/brass_casing_from_log_using_deployer',
        'create:crafting/materials/rose_quartz',
        'createaddition:crafting/redstone_relay',
        'createaddition:crafting/small_connector_copper',
        'createaddition:crafting/festive_spool',
        'createaddition:crafting/electrum_spool',
        'createaddition:crafting/gold_spool',
        'createaddition:crafting/copper_spool',
        'createaddition:crafting/spool',
        'createaddition:crafting/small_light_connector',
        'tfmg:crafting/electric_casing',
        'tfmg:casting/steel',
        'tfmg:casting/amogus',
        'createaddition:crafting/portable_energy_interface',
        'create:crafting/kinetics/encased_fan',
        'create:crafting/kinetics/millstone',
        'create:crafting/kinetics/mechanical_press',
        'create:crafting/kinetics/mechanical_mixer',
        'create:crafting/kinetics/rope_pulley',
        'create:crafting/kinetics/mechanical_drill',
        'create:crafting/kinetics/mechanical_saw',
        'create:crafting/kinetics/deployer',
        'create:crafting/kinetics/portable_storage_interface',
        'create:crafting/kinetics/mechanical_piston',
        'create:crafting/kinetics/mechanical_bearing',
        'create:crafting/kinetics/windmill_bearing',
        'create:crafting/kinetics/gantry_carriage',
        'create:crafting/kinetics/sticker',
        'supplementaries:rope',
        'farmersdelight:rope',
        'create:crafting/kinetics/cuckoo_clock',
        'create:crafting/kinetics/large_water_wheel',
        'create:crafting/kinetics/gearbox',
        'create:crafting/kinetics/gearboxfrom_conversion',
        'create:crafting/kinetics/vertical_gearboxfrom_conversion',
        'create:crafting/kinetics/vertical_gearbox',
        'create:crafting/logistics/andesite_tunnel',
        'create:crafting/logistics/andesite_funnel',
        'create:pressing/sugar_cane',
        'tconstruct:smeltery/melting/metal/steel/ingot',
        'tconstruct:smeltery/melting/metal/steel/block',
        'tconstruct:smeltery/melting/metal/steel/nugget',
        'tconstruct:smeltery/melting/metal/steel/plates',
        'tconstruct:smeltery/melting/metal/steel/rod',
        'tconstruct:smeltery/melting/metal/steel/wire',
        'tconstruct:tools/materials/melting/steel',
        'tfmg:crushing/limesand',
        'functionalstorage:fluid_1',
        'functionalstorage:fluid_2',
        'functionalstorage:fluid_4',
        'functionalstorage:compacting_drawer',
        'functionalstorage:compacting_framed_drawer',
        'functionalstorage:simple_compacting_drawer',
        'functionalstorage:framed_simple_compacting_drawer',
        'functionalstorage:ender_drawer',
        'functionalstorage:netherite_upgrade',
        'functionalstorage:diamond_upgrade',
        'functionalstorage:void_upgrade',
        'functionalstorage:controller_extension',
        'functionalstorage:framed_controller_extension',
        'functionalstorage:storage_controller',
        'functionalstorage:framed_storage_controller',
        'vintageimprovements:craft/spring_coiling_machine',
        'tfmg:crafting/copycat_cable_block',
        'tfmg:crafting/copper_wire_plastic',
        'tfmg:crafting/copper_wire',
        'create_sa:zinc_handle_recipe',
        'create_sa:brass_drill_head_recipe',
        'tfmg:sequenced_assembly/steel_mechanism',
        'tfmg:sequenced_assembly/turbine_engine',
        'tfmg:sequenced_assembly/gasoline_engine',
        'tfmg:sequenced_assembly/lpg_engine',
        'tfmg:crafting/casting_spout',
        'createaddition:crafting/diamond_grit_sandpaper',
        'tconstruct:smeltery/alloys/molten_manyullyn',
        'functionalstorage:linking_tool',
        'functionalstorage:configuration_tool',
        'tfmg:polarizing/magnetic_ingot',
        'tfmg:milling/limesand',
        'create_dd:crafting/kinetics/kinetic_motor',
        'create_dd:crafting/fan_catalyst/splashing_sail',
        'create_dd:crafting/fan_catalyst/haunting_sail',
        'create_dd:crafting/fan_catalyst/smoking_sail',
        'create_dd:crafting/fan_catalyst/blasting_sail',
        'create_dd:crafting/fan_catalyst/freezing_sail',
        'create_dd:crafting/fan_catalyst/sanding_sail',
        'create_dd:mechanical_crafting/superheating_sail',
        'create_dd:crafting/item_interface',
        'create_dd:crafting/gearbox_from_vertical_gearbox',
        'create_dd:crafting/contraption_controls',
        'create_dd:crafting/vertical_gearbox_from_gearbox',
        'create_dd:crafting/kinetic_motor',
        'create_dd:crafting/gearbox',
        'create_dd:crafting/adj_chain_gearshift',
        'create_dd:crafting/mechanical_roller',
        'create_dd:crafting/deployer',
        'create_dd:crafting/vertical_gearbox',
        'create_dd:crafting/controls',
        'create_dd:crafting/mechanical_arm',
        'create_oppenheimered:deploying/precision_mechanism_from_telecore',
        'create_dd:crafting/rotation_speed_controller',
        'create_dd:crafting/mechanism_display_board',
        'create_dd:industrial_iron/mechanism_display_board_indust',
        'create_dd:crafting/equipment/flipped_deforester_saw',
        'create_dd:mechanical_crafting/excavation_drill',
        'apotheosis:library',
        'apotheosis:enchanting/ender_library',
        'create:crafting/kinetics/spout',
        'create:crafting/kinetics/portable_fluid_interface',
        'create:crafting/kinetics/item_drain',
        'create:crafting/kinetics/hose_pulley',
        'create:crafting/kinetics/smart_fluid_pipe',
        'tconstruct:smeltery/seared/melter',
        'tconstruct:smeltery/scorched/alloyer',
        'create_dd:compacting/steel_ingot',
        'create_dd:crafting/steel_ingot_from_compacting',
        'create_dd:crafting/steel_ingot_from_decompacting',
        'create_dd:crafting/deforester_saw',
        'create_dd:mechanical_crafting/forest_ravager',
        'create:industrial_iron_block_from_ingots_iron_stonecutting',
        'create_dd:crafting/accelerator_motor',
        'create_dd:mixing/condense_milk',
        'create_dd:mixing/cream',
        'create_dd:mixing/vanilla',
        'create_dd:mixing/vanilla_milkshake',
        'create_dd:mixing/strawberry',
        'create_dd:mixing/strawberry_milkshake',
        'create_dd:mixing/hot_chocolate',
        'create_dd:mixing/chocolate_milkshake',
        'create_dd:mixing/glowberry',
        'create_dd:mixing/glowberry_milkshake',
        'create_dd:mixing/caramel',
        'create_dd:mixing/caramel_milkshake',
        'vintageimprovements:pressing/refined_radiance',
        'create_dd:emptying/chromatic_waste',
        'createaddition:pressing/zinc_ingot',
        'vintageimprovements:pressing/tin_ingot',
        'createaddition:crafting/modular_accumulator_electrum',
        'vintageimprovements:rolling/andesite_plate',
        'tconstruct:common/materials/copper_nugget_from_ingot',
        'tconstruct:smeltery/casting/metal/copper/nugget_gold_cast',
        'tconstruct:smeltery/casting/metal/copper/nugget_sand_cast',
        'tconstruct:common/materials/copper_ingot_from_nuggets',
        'tfmg:item_application/steel_casing_using_deployer',
        'tfmg:item_application/steel_casing',
        'create_dd:sequenced_assembly/integrated_mechanism',
        'create_dd:crafting/steam_engine',
        'create_dd:crafting/spout',
        'create_dd:crafting/hydraulic_press',
        'create_dd:crafting/fluid_interface',
        'create_dd:crafting/brass_hand',
        'create_oppenheimered:deploying/electron_tube_from_notor_gizmo',
        'create:crafting/logistics/brass_funnel',
        'create:crafting/logistics/brass_tunnel',
        'create:crafting/kinetics/sequenced_gearshift',
        'create_dd:sequenced_assembly/sealed_mechanism',
        'advancedperipherals:peripheral_casing',
        'computercraft:computer_advanced',
        'computercraft:pocket_computer_advanced',
        'minecraft:minecraft.potion.levitation.effect.minecraft.levitation..Duration..2400.to.minecraft.potion.flying.effect.attributeslib.flying..Duration..9600',
        'minecraft:minecraft.potion.flying.effect.attributeslib.flying..Duration..9600.to.minecraft.potion.flying.effect.attributeslib.flying..Duration..18000',
        'minecraft:minecraft.potion.flying.effect.attributeslib.flying..Duration..18000.to.minecraft.potion.flying.effect.attributeslib.flying..Duration..36000',
        'minecraft:minecraft.potion.flying.effect.attributeslib.flying..Duration..9600.to.minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..9600',
        'minecraft:minecraft.splash_potion.levitation.effect.minecraft.levitation..Duration..2400.to.minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..9600',
        'minecraft:minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..9600.to.minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..18000',
        'minecraft:minecraft.potion.flying.effect.attributeslib.flying..Duration..18000.to.minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..18000',
        'minecraft:minecraft.potion.flying.effect.attributeslib.flying..Duration..18000.to.minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..18000',
        'minecraft:minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..18000.to.minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..36000',
        'minecraft:minecraft.lingering_potion.levitation.effect.minecraft.levitation..Duration..2400.to.minecraft.lingering_potion.flying.effect.attributeslib.flying..Duration..9600',
        'minecraft:minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..9600.to.minecraft.lingering_potion.flying.effect.attributeslib.flying..Duration..9600',
        'minecraft:minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..18000.to.minecraft.lingering_potion.flying.effect.attributeslib.flying..Duration..18000',
        'minecraft:minecraft.lingering_potion.flying.effect.attributeslib.flying..Duration..9600.to.minecraft.lingering_potion.flying.effect.attributeslib.flying..Duration..18000',
        'minecraft:minecraft.lingering_potion.flying.effect.attributeslib.flying..Duration..18000.to.minecraft.lingering_potion.flying.effect.attributeslib.flying..Duration..36000',
        'minecraft:minecraft.splash_potion.flying.effect.attributeslib.flying..Duration..36000.to.minecraft.lingering_potion.flying.effect.attributeslib.flying..Duration..36000',
        'minecraft:jei.tipped.arrow.item.minecraft.tipped_arrow.effect.flying',
        

    ]
    
    let recipeOutputs = [
        'create_sa:brass_jetpack_chestplate',
        'create_sa:copper_jetpack_chestplate',
        'create_sa:andesite_jetpack_chestplate',
        'create_sa:netherite_jetpack_chestplate',
        'minecraft:elytra',
        'tconstruct:slime_chestplate',
        'createaddition:capacitor',
        'createaddition:tesla_coil',
        'createaddition:accumulator',
        'createaddition:alternator',
        'createaddition:electric_motor',
        'createaddition:large_connector',
    ]
    
    let recipeInputs = [];
    
    recipeIds.forEach(id => {
        event.remove({ id: id });
    })
    
    recipeOutputs.forEach(output => {
        event.remove({ output: output });
    })
    
    recipeInputs.forEach(input => {
        event.remove({ input: input });
    })
    let removeTFMGItems = [
        'stator', 'electric_post', 'electric_diode', 'resistor', 'copper_coil','electric_pump', 'diagonal_cable_block', 'cable_tube', 'neon_tube', 'copper_cable_hub', 
        'steel_cable_hub', 'aluminum_cable_hub', 'copper_cable_hub', 'steel_casing_cable_hub', 'heavy_cable_hub', 'voltmeter', 'cable_connector', 'energy_meter',
        'traffic_light', 'voltage_observer', 'light_bulb', 'rgb_light_bulb', 'brass_cable_hub', 'segmented_display', 'fuse_block', 'capacitor', 'accumulator', 'polarizer',
        'transistor', 'converter', 'generator', 'rotor', 'electric_motor', 'galvanic_cell']
    removeTFMGItems.forEach(item => {
        event.remove({output: 'tfmg:' + item})
    })
})
