StartupEvents.registry('item', event => {
    let tool = (name) => {
        let id = name.toLowerCase()
        event.create(id, 'sword').tier('tool').texture("kubejs:item/" + id).displayName(name).rarity("common")
    }
	event.create('calcite_catalyst').displayName('Calcite Catalyst').texture('kubejs:item/calcite_catalyst')
	event.create('limestone_shard').displayName('Limestone Shard').texture('kubejs:item/limestone_shard')
	event.create('lapis_lazuli_catalyst').displayName('Lapis Lazuli Catalyst').texture('kubejs:item/lapis_lazuli_catalyst')
	event.create('asurine_shard').displayName('Asurine Shard').texture('kubejs:item/asurine_shard')
	event.create('ochrum_shard').displayName('Ochrum Shard').texture('kubejs:item/ochrum_shard')
	event.create('veridium_shard').displayName('Veridium Shard').texture('kubejs:item/veridium_shard')
	event.create('crimsite_shard').displayName('Crimsite Shard').texture('kubejs:item/crimsite_shard')
	event.create('obsidian_alloy').displayName('Obsidian Alloy').texture('kubejs:item/obsidian_alloy')
	event.create('bauxite_shard').displayName('Bauxite Shard').texture('kubejs:item/bauxite_shard')
	event.create('alumina_crystal').displayName('Alumina Crystal').texture('kubejs:item/alumina_crystal')
	event.create('crushed_deepslate').displayName('Crushed Deepslate').texture('kubejs:item/crushed_deepslate')
	event.create('sturdy_shards').displayName('Sturdy Shards').texture('kubejs:item/sturdy_shards')
	event.create('deepslate_alloy').displayName('Deepslate Alloy').texture('kubejs:item/deepslate_alloy')
	event.create('sulfuric_crystal').displayName('Sulfuric Crystal').texture('kubejs:item/sulfuric_crystal')
	event.create('empty_tube').displayName('Empty Tube').texture('kubejs:item/empty_tube')
	event.create("copper_machine").tooltip("Used to make basic tinkers construct and fluid items").displayName("Copper Machine").parentModel("kubejs:item/copper_machine")
	event.create("andesite_machine").tooltip("Used to make basic machines for create").displayName("Andesite Machine").parentModel("kubejs:item/andesite_machine")
	event.create("brass_machine").tooltip("Used to make mid game stuff such as steam engines").displayName("Brass Machine").parentModel("kubejs:item/brass_machine")
	event.create("steel_machine").tooltip("Used to make heavy machinery such as a pumpjack").displayName("Steel Machine").parentModel("kubejs:item/steel_machine")
	// event.create("tsteel_machine").tooltip("A steel machine that is missing a few parts").displayName("Incomplete Steel Machine").parentModel("kubejs:item/steel_machine")
	event.create("blazing_machine").tooltip("Used to make controllers for large smelteries and foundries").displayName("Blazing Machine").parentModel("kubejs:item/blazing_machine")
	event.create("motherboard").displayName("Motherboard").texture("kubejs:item/motherboard")
	event.create("graphics_unit").displayName("Graphics Unit").texture("kubejs:item/graphics_unit")
	event.create("hard_drive").displayName("Hard Drive").texture("kubejs:item/hard_drive")
	event.create("incomplete_computer").tooltip("A computer that is missing a few parts").displayName("Incomplete Computer").parentModel("kubejs:item/incomplete_computer")
	event.create("nickel_tube").displayName("Nickel Tube").texture("kubejs:item/nickel_tube")
	tool('Saw')
	event.create('drill_head').displayName('Drill Head').texture('kubejs:item/drill_head')
	event.create('saw_blade').displayName('Saw Blade').texture('kubejs:item/saw_blade')

	event.create('andesite_upgrade_smithing_template').displayName('Smithing Template').texture('kubejs:item/andesite_upgrade_smithing_template')
	event.create('brass_upgrade_smithing_template').displayName('Smithing Template').texture('kubejs:item/brass_upgrade_smithing_template')
	event.create('copper_upgrade_smithing_template').displayName('Smithing Template').texture('kubejs:item/copper_upgrade_smithing_template')
})
