StartupEvents.registry('fluid', event => {
    event.create('liquid_garnish')
    .thinTexture(0xbed3c2)
    .bucketColor(0xbed3c2)
    .displayName('Garnish')
    .noBucket()
    .noBlock()

    event.create('zinc_solution')
    .thinTexture(0xc8e1cd)
    .bucketColor(0xc8e1cd)
    .displayName('Zinc Solution')
    .noBucket()
    .noBlock()

    event.create('gold_solution')
    .thinTexture(0xc8e1cd)
    .bucketColor(0xc8e1cd)
    .displayName('Gold Solution')
    .noBucket()
    .noBlock()

    event.create('sulfuric_solution')
    .thinTexture(0xc9efa1)
    .bucketColor(0xc9efa1)
    .displayName('Sulfuric Solution')
    .noBucket()
    .noBlock()

    event.create('crystalline_acid')
    .thinTexture(0x9ccfda)
    .bucketColor(0x9ccfda)
    .displayName('Crystalline Acid')
    .noBucket()
    .noBlock()

    event.create('nitrogen')
    .thinTexture(0xe6ebee)
    .bucketColor(0xe6ebee)
    .displayName('Nitrogen')
    .noBucket()
    .noBlock()

    event.create('purified_water')
    .thinTexture(0x82bfde)
    .bucketColor(0x82bfde)
    .displayName('Purified Water')
    .noBlock()

    event.create('enriched_water')
    .thinTexture(0xd2e1e3)
    .bucketColor(0xd2e1e3)
    .displayName('Enriched Water')
    .noBlock()

    event.create('glow_solution')
    .thinTexture(0xfaf478)
    .bucketColor(0xfaf478)
    .displayName('Glow Solution')
    .noBlock()

    event.create('volcanic_acid')
    .thinTexture(0xf2acb9)
    .bucketColor(0xf2acb9)
    .displayName('Volcanic Acid')
    .noBucket()
    .noBlock()

    event.create('molten_redstone')
    .thinTexture(0xe74f4f)
    .bucketColor(0xe74f4f)
    .displayName('Molten Redstone')
    .noBlock()
})
