StartupEvents.registry('item', event => {
	event.create('calcite_catalyst')
		.displayName('Calcite Catalyst')
	event.create('limestone_shard')
		.displayName('Limestone Shard')
	event.create('lapis_lazuli_catalyst')
		.displayName('Lapis Lazuli Catalyst')
	event.create('asurine_shard')
		.displayName('Asurine Shard')
	event.create('ochrum_shard')
		.displayName('Ochrum Shard')
	event.create('veridium_shard')
		.displayName('Veridium Shard')
	event.create('crimsite_shard')
		.displayName('Crimsite Shard')
	event.create('obsidian_alloy')
		.displayName('Obsidian Alloy')
	event.create('crushed_deepslate')
		.displayName('Crushed Deepslate')
	event.create('sturdy_shards')
		.displayName('Sturdy Shards')
	event.create('deepslate_alloy')
		.displayName('Deepslate Alloy')
	event.create('sulfuric_crystal')
		.displayName('Sulfuric Crystal')
})