StartupEvents.registry('item', event => {
    event.create('incomplete_netherrack', 'create:sequenced_assembly')
        .displayName('Incomplete Netherrack')
    event.create('incomplete_lapis_lazuli_catalyst', 'create:sequenced_assembly')
        .displayName('Incomplete Lapis Lazuli Catalyst')
    event.create('incomplete_asurine_shard', 'create:sequenced_assembly')
        .displayName('Incomplete Asurine Shard')
    event.create('incomplete_ochrum_shard', 'create:sequenced_assembly')
        .displayName('Incomplete Ochrum Shard')
    event.create('incomplete_veridium_shard', 'create:sequenced_assembly')
        .displayName('Incomplete Veridium Shard')
    event.create('incomplete_crimsite_shard', 'create:sequenced_assembly')
        .displayName('Incomplete Crimsite Shard')
    event.create('incomplete_sulfuric_crystal', 'create:sequenced_assembly')
        .displayName('Incomplete Sulfuric Crystal')
    event.create('incomplete_bauxite_shard', 'create:sequenced_assembly')
        .displayName('Incomplete Bauxite Shard')
    event.create('incomplete_alumina_crystal', 'create:sequenced_assembly')
        .displayName('Incomplete Alumina Crystal')
})
