StartupEvents.registry('item', event => {
    event.create('incomplete_netherrack')
        .displayName('Incomplete Netherrack')
    event.create('incomplete_lapis_lazuli_catalyst')
        .displayName('Incomplete Lapis Lazuli Catalyst')
    event.create('incomplete_asurine_shard')
        .displayName('Incomplete Asurine Shard')
    event.create('incomplete_ochrum_shard')
        .displayName('Incomplete Ochrum Shard')
    event.create('incomplete_veridium_shard')
        .displayName('Incomplete Veridium Shard')
    event.create('incomplete_crimsite_shard')
        .displayName('Incomplete Crimsite Shard')
    event.create('incomplete_sulfuric_crystal')
        .displayName('Incomplete Sulfuric Crystal')
    event.create('incomplete_bauxite_shard')
        .displayName('Incomplete Bauxite Shard')
    event.create('incomplete_alumina_crystal')
        .displayName('Incomplete Alumina Crystal')
    event.create('incomplete_andesite_machine')
        .displayName('Incomplete Andesite Machine')
        .texture("kubejs:item/incomplete_andesite_machine")
        .parentModel("kubejs:item/incomplete_andesite_machine")
    event.create('incomplete_brass_machine')
        .displayName('Incomplete Brass Machine')
        .texture("kubejs:item/incomplete_brass_machine")
        .parentModel("kubejs:item/incomplete_brass_machine")
    event.create('incomplete_steel_machine')
        .displayName('Incomplete Steel Machine')
        .texture("kubejs:item/incomplete_steel_machine")
        .parentModel("kubejs:item/incomplete_steel_machine")
    event.create('incomplete_blazing_machine')
        .displayName('Incomplete Blazing Machine')
        .texture("kubejs:item/incomplete_blazing_machine")
        .parentModel("kubejs:item/incomplete_blazing_machine")
    event.create('incomplete_copper_machine')
        .displayName('Incomplete Copper Machine')
        .texture("kubejs:item/incomplete_copper_machine")
        .parentModel("kubejs:item/incomplete_copper_machine")
    event.create('incomplete_electrum_shard')
        .displayName('Incomplete Electrum Crystal')
})
