ServerEvents.recipes(event => {
    event.recipes.vintageimprovementsHammering(Item.of('northstar:tungsten_sheet', 1), 'northstar:tungsten_ingot', 2).id('kubejs:hammering/tungsten_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('tconstruct:pig_iron_sheet', 1), 'tconstruct:pig_iron_ingot', 2).id('kubejs:hammering/pig_iron_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('tfmg:lead_sheet', 1), 'tfmg:lead_ingot', 2).id('kubejs:hammering/lead_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('create_dd:bronze_sheet', 1), 'create_dd:bronze_ingot', 2).id('kubejs:hammering/bronze_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('tfmg:lead_sheet', 1), 'tfmg:lead_ingot', 2).id('kubejs:hammering/lead_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('tfmg:cast_iron_sheet', 1), 'tfmg:cast_iron_ingot', 2).id('kubejs:hammering/cast_iron_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('tconstruct:cobalt_sheet', 1), 'tconstruct:cobalt_ingot', 2).id('kubejs:hammering/cobalt_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('tconstruct:hepatizon_sheet', 1), 'tconstruct:hepatizon_ingot', 2).id('kubejs:hammering/hepatizon_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('tconstruct:manyullyn_sheet', 1), 'tconstruct:manyullyn_ingot', 2).id('kubejs:hammering/manyullyn_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('tconstruct:queens_slime_sheet', 1), 'tconstruct:queens_slime_ingot', 2).id('kubejs:hammering/queens_slime_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('tconstruct:rose_gold_sheet', 1), 'tconstruct:rose_gold_ingot', 2).id('kubejs:hammering/rose_gold_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('tconstruct:slimesteel_sheet', 1), 'tconstruct:slimesteel_ingot', 2).id('kubejs:hammering/slimesteel_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('vintageimprovements:vanadium_sheet', 1), 'vintageimprovements:vanadium_ingot', 2).id('kubejs:hammering/vanadium_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('create_dd:industrial_iron_sheet', 1), 'create_dd:industrial_iron_ingot', 2).id('kubejs:hammering/industrial_iron_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('create_dd:shadow_steel_sheet', 1), 'create_dd:shadow_steel_ingot', 2).id('kubejs:hammering/shadow_steel_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('create_dd:refined_radiance_sheet', 1), 'create_dd:refined_radiance', 2).id('kubejs:hammering/refined_radiance_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('vintageimprovements:cast_iron_sheet', 1), 'vintageimprovements:cast_iron_ingot', 2).id('kubejs:hammering/cast_iron_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('vintageimprovements:amethyst_bronze_sheet', 1), 'vintageimprovements:amethyst_bronze_ingot', 2).id('kubejs:hammering/amethyst_bronze_sheet')
    event.recipes.vintageimprovementsHammering(Item.of('create_dd:mithril_sheet', 1), 'create_dd:mithril_ingot', 2).id('kubejs:hammering/mithril_sheet')
});